# Generated by Django 4.2 on 2023-08-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EuroBought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_bought', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EuroSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_sold', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OtherBought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_name', models.CharField(max_length=50)),
                ('course_bought', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OtherSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_name', models.CharField(max_length=50)),
                ('course_sold', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PoundBought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_bought', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PoundSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_sold', models.PositiveIntegerField()),
            ],
        ),
    ]
