# Generated by Django 4.2 on 2023-08-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_eurobought_quantity_eurosold_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eurosold',
            name='course_sold',
            field=models.PositiveIntegerField(blank=True, default=1.96, null=True),
        ),
    ]
