# Generated by Django 4.2 on 2023-08-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_eurosold_course_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eurobought',
            name='course_bought',
            field=models.FloatField(blank=True, default=1.94, null=True),
        ),
        migrations.AlterField(
            model_name='eurosold',
            name='course_sold',
            field=models.FloatField(blank=True, default=1.96, null=True),
        ),
        migrations.AlterField(
            model_name='otherbought',
            name='course_bought',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='othersold',
            name='course_sold',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='poundbought',
            name='course_bought',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='poundsold',
            name='course_sold',
            field=models.FloatField(),
        ),
    ]
